services:
  app:
    container_name: ssm-app-prod
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
      args:
        VITE_API_URL: /api
      tags:
        - ssh-key-manager_app:production
    ports:
      - "80:80"
    volumes:      
      # Database persistence
      - ./data/db:/app/db
      # Configuration files
      - ./data/config/config.toml:/app/config.toml:ro
      - ./data/auth/.htpasswd:/app/.htpasswd:ro
      # SSH keys (read-only for security)
      - ./data/ssh-keys:/app/keys:ro
      # Logs
      - ./data/logs:/app/logs
    environment:
      - CONFIG=/app/config.toml
      - DATABASE_URL=sqlite:///app/db/ssm.db
      - RUST_LOG=warn
      - RUST_BACKTRACE=0
    networks:
      - ssm-network
    restart: always
    healthcheck:
      test: ["CMD", "/app/health-check.sh"]
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 30s
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    user: "1000:1000"  # Adjust to your user/group ID

networks:
  ssm-network:
    driver: bridge