name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
#    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # vscode-github-actions: ignore
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        push: true
        #cache-from: type=registry,ref=styliteag/ssh-key-manager:latest
        #cache-to: type=inline
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          styliteag/ssh-key-manager:latest
          ghcr.io/${{ github.repository }}/ssh-key-manager:latest
#    - name: Build and push to GitHub Container Registry
#      uses: docker/build-push-action@v6
#      with:
#        push: true
#        tags: ghcr.io/${{ github.repository }}/ssh-key-manager:latest
