name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # vscode-github-actions: ignore
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: styliteag/ssh-key-manager:latest
    - name: Build and push to GitHub Container Registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}/ssh-key-manager:latest
