name: GHCR Cleanup

on:
  schedule:
    - cron: '17 3 * * 0'

permissions:
  contents: read
  packages: read

jobs:
  cleanup:
    name: Prune old GHCR versions
    runs-on: ubuntu-latest
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: styliteag
          container: ssm
          dry-run: true # Dry-run first, then change to `false`
          keep-younger-than: 7 # days
          keep-last: 2
          prune-untagged: true