name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  secret-detection:
    name: Secret Detection
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for comprehensive scanning
    
    - name: Run TruffleHog OSS
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
        head: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event.after }}
        extra_args: --debug --only-verified
      continue-on-error: true
    
    - name: Run GitLeaks
      uses: gitleaks/gitleaks-action@v2
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not needed for personal accounts.
    
    - name: Custom Secret Pattern Check
      run: |
        echo "🔍 Running custom secret patterns..."
        
        # Check for patterns that might not be caught by other tools
        SECRETS_FOUND=0
        
        # Define exclusions for test directories and files
        EXCLUDE_DIRS="--exclude-dir=.git --exclude-dir=.github --exclude-dir=.githooks --exclude-dir=backend/src/tests --exclude-dir=frontend/src/test --exclude-dir=tests"
        EXCLUDE_FILES="--exclude=*.test.* --exclude=*.spec.* --exclude=*test*.rs --exclude=*test*.js --exclude=*test*.ts --exclude=.secrets-whitelist"
        
        # Private keys (fixed grep syntax)
        if grep -rE -- "-----BEGIN.*PRIVATE KEY-----" . $EXCLUDE_DIRS $EXCLUDE_FILES; then
          echo "❌ Private keys detected"
          SECRETS_FOUND=1
        fi
        
        # Custom API key patterns (exclude test values)
        if grep -rE "(api_key|apikey|secret_key|secretkey).*=.*[\"'][^\"']{20,}[\"']" . $EXCLUDE_DIRS $EXCLUDE_FILES | grep -v "test\|example\|demo\|sk_test"; then
          echo "❌ API keys detected"
          SECRETS_FOUND=1
        fi
        
        # Long passwords (exclude test passwords)
        if grep -rE "password.*=.*[\"'][^\"']{12,}[\"']" . $EXCLUDE_DIRS $EXCLUDE_FILES | grep -v "test\|example\|demo\|hash"; then
          echo "❌ Long passwords detected"  
          SECRETS_FOUND=1
        fi
        
        # Database URLs with passwords (exclude localhost/test)
        if grep -rE "(postgres|mysql|mongodb)://[^:]+:[^@]{8,}@" . $EXCLUDE_DIRS $EXCLUDE_FILES | grep -v "localhost\|test\|example"; then
          echo "❌ Database URLs with passwords detected"
          SECRETS_FOUND=1
        fi
        
        if [ $SECRETS_FOUND -eq 1 ]; then
          echo "🚨 Custom secret patterns detected! Check the output above."
          exit 1
        else
          echo "✅ No custom secret patterns detected"
        fi
    
    - name: Check whitelist configuration
      run: |
        if [ -f ".secrets-whitelist" ]; then
          echo "✅ Secrets whitelist found"
          echo "📋 Whitelist summary:"
          grep -c "^[^#]" .secrets-whitelist || echo "0 entries"
          echo "💡 VALUE entries: $(grep -c "^VALUE:" .secrets-whitelist || echo "0")"
        else
          echo "⚠️ No secrets whitelist found"
        fi

  dependency-check:
    name: Dependency Vulnerability Scan  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  git-hooks-check:
    name: Verify Git Hooks Setup
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check git hooks infrastructure
      run: |
        echo "🔍 Checking git hooks infrastructure..."
        
        # Check if shared hooks exist
        if [ -d ".githooks" ] && [ -f ".githooks/pre-commit" ]; then
          echo "✅ Shared git hooks found"
        else
          echo "❌ Shared git hooks missing"
          exit 1
        fi
        
        # Check if installation script exists
        if [ -f "install-hooks.sh" ] && [ -x "install-hooks.sh" ]; then
          echo "✅ Hook installation script found and executable"
        else
          echo "❌ Hook installation script missing or not executable"
          exit 1
        fi
        
        # Check if whitelist exists
        if [ -f ".secrets-whitelist" ]; then
          echo "✅ Secrets whitelist found"
        else
          echo "❌ Secrets whitelist missing"
          exit 1
        fi
        
        # Test hook installation (dry run)
        echo "🧪 Testing hook installation..."
        ./install-hooks.sh
        
        echo "✅ All git hooks infrastructure verified"